---
name: Deploy to Pages

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: mkdocs build
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/configure-pages@v5.0.0
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: mkdocs build
      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: './site'
      - id: deployment
        uses: actions/deploy-pages@v4.0.5
